### ISSUE TITLE
Object align support

### ISSUE THREAD

**Issue by AldonIsenberg11** [adrianlee44/atom-aligner-coffeescript#3]
Sweet plugin, however I was hoping that it would also structure the colons the same way the `=` sign

or at least the option to include that

ex.

Current:

```
   object =
      key1:      value1
      keytest2:  value2
      key3:      value3
``` 

Requested:

```
   object =
      key1      : value1
      keytest2  : value2
      key3      : value3
```

**Comment by adrianlee44** [comment]
You can do that with the existing package but will need to update some options.

If you go to `aligner-coffeescript` settings, change "Padding for :" to "left" and also enable "Left space for :", you should get what you want.
